---
title: "In Class exercise 6"
description: |
  GeoVisual Analytics
author:
  - name: Raunak Kapur 
    affiliation: Singapore Management University
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
packages = c('rmarkdown','sf','tmap','tidyverse','clock','lubridate','sftime')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}

```

```{r}
schools <- read_sf("data/Schools.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")

```


```{r}
pubs<-read_sf("data/Pubs.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")

apartments<-read_sf("data/Apartments.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")
buildings<-read_sf("data/buildings.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")
employers<-read_sf("data/Employers.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")
restaurant<-read_sf("data/Restaurants.csv", 
                   options = "GEOM_POSSIBLE_NAMES=location")
```

```{r}
tmap_mode("view")
tm_shape(buildings)+
tm_polygons(col = "grey60",
           size = 1,
           border.col = "black",
           border.lwd = 1)
tmap_mode("plot")

```

Note: interactive tmap_mode is supposed to be switched off after we are done

```{r}
tmap_mode("plot")
tm_shape(buildings)+
tm_polygons(col = "grey60",
           size = 1,
           border.col = "black",
           border.lwd = 1) +
tm_shape(employers) +
  tm_dots(col = "red")

```

# Movement Data

```{r eval=FALSE}
logs <- read_sf("data/ParticipantStatusLogs1.csv", 
                options = "GEOM_POSSIBLE_NAMES=currentLocation")
```

```{r eval=FALSE}
logs_selected<-logs%>%
  mutate(Timestamp=date_time_parse(timestamp,zone="",format="%Y-%m-%dT%H:%M:%S"))%>%
  mutate(day=get_day(Timestamp))%>%
  filter(currentMode=="Transport")
```

```{r eval=FALSE}
write_rds(logs_selected,"data/logs_selected.rds")

```

```{r}
logs_selected<-read_rds("data/logs_selected.rds")
```

```{r}
hex <- st_make_grid(buildings, 
                    cellsize=100, 
                    square=FALSE) %>%
  st_sf() %>%
  rowid_to_column('hex_id')
plot(hex)
```

```{r}
points_in_hex <- st_join(logs_selected, 
                         hex, 
                         join=st_within)

```

```{r}
points_in_hex <- st_join(logs_selected, 
                        hex, 
                        join=st_within) %>%
  st_set_geometry(NULL) %>%
  count(name='pointCount', hex_id)
head(points_in_hex)

```
```{r}
hex_combined <- hex %>%
  left_join(points_in_hex, 
            by = 'hex_id') %>%
  replace(is.na(.), 0)

```

```{r}
tm_shape(hex_combined %>%
           filter(pointCount > 0))+
  tm_fill("pointCount",
          n = 8,
          style = "quantile") +
  tm_borders(alpha = 0.1)

```

